In [1]:
#exception/error handling

In [2]:
#try and except

In [3]:
try:
    f=open('all.txt')
except:
    print('file does not exist')

file does not exist

In [4]:
try:
    f=open('a1.txt')
    print(var1)
except:
    print("file does not exist")

file does not exist

In [5]:
try:
    f=open('a1.txt')
    print(var1)
except FileNotFoundError:
    print("file does not exist")

NameError: name 'var1' is not defined

In [7]:
try:
    f=open('a1.txt')
    print(var1)
except FileNotFoundError:
    print("file does not exist")
except Exception:
    print("something went wrong")

something went wrong

In [8]:
try:
    f=open('a1.txt')
    print(var1)
except FileNotFoundError:
    print("file does not exist")
except Exception as e:
    print(e)

name 'var1' is not defined

In [9]:
try:
    f=open('a1.txt')
except FileNotFoundError:
    print("file does not exist")
except Exception as e:
    print(e)
else:
    print(f.read())
    f.close()

this is the first line

In [11]:
try:
    f=open('a1.txt')
    print(var1)
except FileNotFoundError:
    print("file does not exist")
except Exception as e:
    print(e)
else:
    print(f.read())
    f.close()
finally:
    print("run complete")

name 'var1' is not defined
run complete

In [12]:
try:
    f=open('a1.txt')
    if f.name=='a1.txt':
        raise Exception
except FileNotFoundError:
    print("file does not exist")
except Exception as e:
    print(e)
else:
    print(f.read())
    f.close()
finally:
    print("run complete")

run complete

In [18]:
try:
    a = int(input("Enter first number: "))
    b = int(input("Enter second number: "))

    result = a / b
    print("Division =", result)

except ZeroDivisionError:
    print("Cannot divide by zero!")

except ValueError:
    print("Please enter valid integer numbers!")

Enter first number:  4
Enter second number:  i

Please enter valid integer numbers!

In [19]:
import pandas as pd

In [21]:
roll=pd.Series([1,2,3,4,5])
name=pd.Series(['sia','ravi','geet','ajinkya','avinash'])
marks=pd.Series([85,67,59,40,90])

In [22]:
df=pd.DataFrame({
    'id':roll,
    'name':name,
    'marks':marks
})

In [23]:
df

   id     name  marks
0   1      sia     85
1   2     ravi     67
2   3     geet     59
3   4  ajinkya     40
4   5  avinash     90

In [26]:
df.shape

(5, 3)

In [27]:
df.ndim

2

In [28]:
df.size

15

In [29]:
df.columns

Index(['id', 'name', 'marks'], dtype='object')

In [32]:
pwd

'C:\\Users\\admin'

In [43]:
import pandas as pd
df = pd.read_csv(r"C:\Users\admin\Downloads\student.csv")

In [44]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [45]:
df.shape

(10, 5)

In [46]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [50]:
df=pd.read_csv(r"C:\Users\admin\Downloads\student1.csv",names=col)

NameError: name 'col' is not defined

In [49]:
df

    1     anil  TE  56.77  22
0   2     amit  TE  59.77  21
1   3   aniket  BE  76.88  19
2   4  ajinkya  TE  69.66  20
3   5     asha  TE  63.28  20
4   6   ayesha  BE  49.55  20
5   7     amar  BE  65.34  19
6   8    amita  BE  68.33  23
7   9     amol  TE  56.75  20
8  10    anmol  BE  78.66  21

In [51]:
col=['roll','name','class','marks','age']

In [52]:
df=pd.read_csv(r"C:\Users\admin\Downloads\student1.csv",names=col)

In [53]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [56]:
df=pd.read_csv(r"C:\Users\admin\Downloads\student3.tsv")

In [57]:
df

  roll\tname\tclass\tmarks\tage
0        1\tanil\tTE\t56.77\t22
1        2\tamit\tTE\t59.77\t21
2      3\taniket\tBE\t76.88\t19
3     4\tajinkya\tTE\t69.66\t20
4        5\tasha\tTE\t63.28\t20
5      6\tayesha\tBE\t49.55\t20
6        7\tamar\tBE\t65.34\t19
7       8\tamita\tBE\t68.33\t23
8        9\tamol\tTE\t56.75\t20
9      10\tanmol\tBE\t78.66\t21

In [58]:
import pandas as pd

df = pd.read_csv(r"C:\Users\admin\Downloads\student3.tsv", sep="\t")
print(df)

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21